version: 2.1

orbs: 
  windows: circleci/windows@2.2.0

jobs:
  checking-out-windows:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: set up LFS config
          shell: bash.exe
          command: |
            printenv LFS_CONFIG | base64 --decode > .lfsconfig
      - run:
          name: sanity check on LFS config
          shell: bash.exe
          command: |
            # should be 2 lines
            wc -l .lfsconfig

workflows:
  main:
    jobs:
      - checking-out-windows
