version: 2.1

orbs: 
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0

jobs:
  checking-out-linux:
    machine:
      image: ubuntu-2004:current
    steps:
      # we will first set up the LFS config, but
      # we need to keep the $HOME/project directory empty (otherwise git clone will complain).
      # hence, this is temporarily placed in a different location first ($HOME)
      - run:
          name: set up LFS config
          command: |
            echo -e "[lfs]\nurl = 'https://${ARTFACTORY_USERNAME}:${ARTFACTORY_API_TOKEN}@kelvintaywl.jfrog.io/artifactory/api/lfs/kelvintaywl-cci-gitlfs-local'" > $HOME/.lfsconfig
      - run:
          name: sanity check on LFS config
          command: |
            # should be 2 lines
            wc -l $HOME/.lfsconfig
      - git-shallow-clone/checkout:
          fetch_depth: 3
      - run:
          name: list files (notice file sizes)
          command: |
            ls -laH
      - run:
          name: restore large file(s)
          command: |
            mv $HOME/.lfsconfig ./.lfsconfig
            git lfs install
            git lfs pull
      - run:
          name: list files again (notice file sizes)
          command: |
            ls -laH

workflows:
  main:
    jobs:
      - checking-out-linux
