version: 2.1

# orbs: 
#   windows: circleci/windows@2.2.0

jobs:
  checking-out-linux:
    # executor:
    #   name: windows/default
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: set up LFS config
          command: |
            printenv LFS_CONFIG | base64 --decode > $HOME/.lfsconfig
      - run:
          name: sanity check on LFS config
          command: |
            # should be 2 lines
            wc -l $HOME/.lfsconfig
      - checkout
      - run:
          name: list files
          command: |
            ls -laH

workflows:
  main:
    jobs:
      - checking-out-linux
