version: 2.1

# orbs: 
#   windows: circleci/windows@2.2.0

jobs:
  checking-out-linux:
    # executor:
    #   name: windows/default
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: set up LFS config
          command: |
            sed -i.bak "s/<USERNAME>/${ARTFACTORY_USERNAME}/" lfsconfig.incomplete
            sed -i.bak "s/<API_TOKEN>/${ARTFACTORY_API_TOKEN}/" lfsconfig.incomplete
            rm lfsconfig.incomplete.bak
            mv lfsconfig.incomplete $HOME/.lfsconfig
      - run:
          name: sanity check on LFS config
          command: |
            # should be 2 lines
            wc -l $HOME/.lfsconfig
      - checkout
      - run:
          name: list files
          command: |
            ls -laH
      - run:
          name: restore large file(s)
          command: |
            mv $HOME/.lfsconfig ./.lfsconfig
            git lfs install
            git lfs pull
      - run:
          name: list files
          command: |
            ls -laH

workflows:
  main:
    jobs:
      - checking-out-linux
